Update README.md
olist/opensource pull request #12
Opened 2019-12-13 21:19 UTC by dA505819

Added Semi-colons and a comma wherever necessary.

2019-12-16 12:25 UTC, raphaelfruneaux requested changes

2019-12-16 12:25 UTC, raphaelfruneaux commented on README.md
> +Simple REST client for python 3.5+ :-
O hífen aqui é proposital?
```suggestion
Simple REST client for python 3.5+ :
```

2019-12-17 07:17 UTC, dA505819 commented
Done!
Thankyou for telling.

2019-12-17 18:17 UTC, dA505819 commented on README.md
> +Simple REST client for python 3.5+ :-
Done

2019-12-18 18:13 UTC, doughss approved these changes

2019-12-18 18:15 UTC, douglashss commented
Thanks @dA505819 :smile:

2019-12-18 18:16 UTC, raphaelfruneaux approved these changes
Thanks a lot @dA505819! 🎉

2019-12-18 18:16 UTC, merged

2019-12-18 18:54 UTC, dA505819 commented
Happy to help!